# Generated by Django 4.2.2 on 2023-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=35, verbose_name='Municipio')),
                ('seccion', models.IntegerField()),
                ('casilla', models.IntegerField()),
                ('ln21', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='DipLocales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.CharField(max_length=35, verbose_name='Municipio')),
                ('partido', models.CharField(max_length=150, verbose_name='Municipio')),
                ('siglas', models.CharField(max_length=35, verbose_name='Municipio')),
                ('nombre', models.CharField(max_length=200, verbose_name='Municipio')),
                ('mun', models.ManyToManyField(to='home.municipio')),
            ],
            options={
                'verbose_name': 'Diputado Local',
                'verbose_name_plural': 'Diputados Locales',
            },
        ),
        migrations.CreateModel(
            name='DipFederales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.CharField(max_length=35, verbose_name='Municipio')),
                ('nombre', models.CharField(max_length=200, verbose_name='Municipio')),
                ('partido', models.CharField(max_length=150, verbose_name='Municipio')),
                ('mun', models.ManyToManyField(to='home.municipio')),
            ],
            options={
                'verbose_name': 'Diputado Federal',
                'verbose_name_plural': 'Diputados Federales',
            },
        ),
    ]
